site_name: HDanke's GD Editor Documentation
docs_dir: docs    
site_dir: site

theme:
  name: mkdocs
  color_mode: auto
  features:
    - navigation.sections
  
markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: README.md
  - Triggers:
      - Object Transform: triggers/object_transforms.md
      - Object Visual: triggers/object_visual.md
      - Follows: triggers/follows.md
      - Area: triggers/area.md
      - Animated: triggers/animate.md
      - Audio: triggers/audio.md
      - Easings: triggers/easings.md
      - Spawning: triggers/spawn.md
      - Stopping: triggers/stop.md
      - Items: triggers/items.md
      - Collisions: triggers/collisions.md
  - Editor:
      - Colors & Layers: editor/colors_layers.md
      - Autobuild: editor/autobuild.md
  - Bugs:
      - Misc: bugs/bugs.md
  - Other:
      - Game Suggestions: suggestions/README.md
      - Misc: suggestions/suggestions.md
      - Sequence Control: suggestions/sequence_control.md
      - Get Parameter: suggestions/parameter_to_item.md
