site_name: HDanke's GD Editor Documentation
theme:
  name: material

nav:
  - Read Me: README.md
  - Triggers:
    - Object Transform: triggers/object_transforms.md
    - Object Visual: triggers/object_visual.md
    - Follows: triggers/follows.md
    - Area: triggers/area.md
    - Animated: triggers/animate_particles.md
    - Audio: triggers/audio.md
    - Easings: triggers/easings.md
    - Spawning: spawn_stop.md
    - Items: triggers/items_and_timers.md
    - Collisions: collisions.md
- Editor
  - Colors & Layers: editor/colors_layers.md
  - Autobuild: editor/autobuild.md
- Bugs: bugs/README.md
 - Misc: bugs/bugs.md
- Other
  - Game Suggestions: suggestions/README.md
    - Misc: suggestions/suggestions.md
    - Sequence Control: suggestions/sequence_control.md
    - Get Parameter: suggestions/parameter_to_item.md
  - Links: 
  - Resources:
  - Credits:
