name: Reformat Markdown Files 
 
on:
  push:
    paths:
      - "data/tables/**"
      - "docs/**"
      - "scripts/mdgen.py"
  workflow_dispatch:
 
jobs:
  mdgen:
    runs-on: ubuntu-latest
 
    permissions:
      contents: write
 
    steps:
      - name: Checkout
        uses: actions/checkout@v6
 
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
 
      - name: Run mdgen
        run: python scripts/mdgen.py
 
      - name: Commit updated markdown
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "reformatted markdown files"
          file_pattern: "docs/**"
 
